// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/banner/Banner.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    PlayList: typeof import('./src/components/play-list/PlayList.vue')['default']
    PlayListItem: typeof import('./src/components/play-list/PlayListItem.vue')['default']
    SongList: typeof import('./src/components/song-list/SongList.vue')['default']
    SongListItem: typeof import('./src/components/song-list/SongListItem.vue')['default']
    SvgIcon: typeof import('./src/components/base/SvgIcon.vue')['default']
    Tabs: typeof import('./src/components/tabs/Tabs.vue')['default']
  }
}

export { }
