// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Banner: typeof import('./src/components/banner/Banner.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    SongList: typeof import('./src/components/song-list/SongList.vue')['default']
    SongListItems: typeof import('./src/components/song-list/SongListItems.vue')['default']
    SvgIcon: typeof import('./src/components/base/SvgIcon.vue')['default']
  }
}

export { }
